---
apiVersion: v2
name: unbyte-cluster
description: An umbrella chart for a workload (k8s) cluster for Unbyte.
type: application
version: 0.9.12
dependencies:
- name: cluster
  version: 0.9.12
  # repository: https://gitlab.com/api/v4/projects/65336103/packages/helm/stable
  repository: file://../cluster
  import-values:
  - data
