{{- with .Values.authSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName | default "vault-approle" }}
  namespace: external-secrets
  labels: {{- include "eso-providers.labels" $ | nindent 4 }}
type: Opaque
data:
  ESO_VAULT_ROLE_ID: {{ tpl .ESO_VAULT_ROLE_ID $ }}
  ESO_VAULT_SECRET_ID: {{ tpl .ESO_VAULT_SECRET_ID $ }}
{{- end }}
