{{- define "cluster.secret" -}}
---
{{- if and (not .Values.hCloud.token.existingSecret) (ne .Values.hCloud.token.value "") }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.hCloud.token.secretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
    {{- if .Values.hCloud.token.move }}
    clusterctl.cluster.x-k8s.io/move: ""
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
data:
  {{ .Values.hCloud.token.secretKey }}: {{ .Values.hCloud.token.value | b64enc }}
{{- end }}
{{- end -}}
