---
apiVersion: v2
name: management-cluster
description: An umbrella chart for unbyte mgt clusters.
type: application
version: 0.10.0-rc.5
dependencies:
- name: cluster
  version: 0.10.0-rc.5
  # repository: https://gitlab.com/api/v4/projects/65336103/packages/helm/stable
  repository: file://../cluster
  import-values:
  - data
