---
apiVersion: v2
name: management-cluster
description: An umbrella chart for unbyte mgt clusters.
type: application
version: 0.10.1
dependencies:
- name: cluster
  version: 0.10.1
  repository: file://../cluster
  import-values:
  - data
