---
# https://external-secrets.io/latest/api/externalsecret/
# https://external-secrets.io/latest/provider/hashicorp-vault/
externalSecrets: {}
# externalSecrets:
#   myExternalSecret:
#     metadata:
#       name: my-external-secret
#       namespace: a-ns
#     spec:
#       refreshInterval: 1h  # Defaults to 1h
#       secretStoreRef:
#         kind: ClusterSecretStore  # Defaults to ClusterSecretStore
#         name: vault-secret-store  # Defaults to vault-secret-store
#       data:
#       # RemoteRef points to the remote secret and defines which secret to fetch.
#       - remoteRef:
#           # Key is the key used in the Provider, mandatory
#           key: external-secrets/push-secrets/my-external-secret
#           # Used to select a specific property of the Provider value (if a map), if supported
#           property: value
#         # The key in the Kubernetes Secret to store the value.
#         secretKey: value
#       target:
#         # Specifies the ExternalSecret ownership details in the created Secret. Options:
#         # - Owner: (default) Creates the Secret and sets .metadata.ownerReferences. If the ExternalSecret is deleted, the Secret will also be deleted.
#         # - Merge: Does not create the Secret but merges data fields into the existing Secret (expects the Secret to already exist).
#         # - Orphan: Creates the Secret but does not set .metadata.ownerReferences. If the Secret already exists, it will be updated.
#         # - None: Does not create or update the Secret (reserved for future use with injector).
#         creationPolicy: Owner  # Defaults to Owner
#         # Specifies what happens to the Secret when data fields are deleted from the provider (e.g., Vault, AWS Parameter Store). Options:
#         # - Retain: (default) Retains the Secret if all Secret data fields have been deleted from the provider.
#         # - Delete: Removes the Secret if all Secret data fields from the provider are deleted.
#         # - Merge: Removes keys from the Secret but not the Secret itself.
#         deletionPolicy: Retain  # Defaults to Retain
#         # Name for the secret to be created on the cluster
#         name: my-external-secret

# https://external-secrets.io/latest/api/pushsecret/
# https://external-secrets.io/latest/provider/hashicorp-vault/#pushsecret
pushSecrets: {}
# pushSecrets:
#   myPushSecret:
#     metadata:
#       name: my-push-secret
#       namespace: a-ns
#     spec:
#       refreshInterval: 1h  # Defaults to 1h
#       # Policy to overwrite existing secrets in the provider on sync: Replace or IfNotExists
#       updatePolicy: Replace  # Defaults to Replace
#       # the provider's secret will be deleted if the PushSecret is deleted: Delete or None
#       deletionPolicy: Delete  # Defaults to Delete
#       secretStoreRefs:
#       - kind: ClusterSecretStore  # Defaults to ClusterSecretStore
#         name: vault-secret-store  # Defaults to vault-secret-store
#       selector:
#         secret:
#           name: my-push-secret
#       # TODO: implement: Alternatively, you can point to a generator that produces values to be pushed
#       # generatorRef:
#       #   apiVersion: external-secrets.io/v1alpha1
#       #   kind: ECRAuthorizationToken
#       #   name: prod-registry-credentials
#       data:
#       - match:
#           # Source Kubernetes secret key to be pushed
#           secretKey: value
#           # RemoteRef points to the remote secret and defines which secret to fetch.
#           remoteRef:
#             # Remote reference (where the secret is going to be pushed). Path in vault.
#             remoteKey: external-secrets/push-secrets/my-push-secret
#             # Field in the Vault KV secret
#             property: value

# https://external-secrets.io/latest/api/generator/vault/
vaultDynamicSecrets:
#   myVaultDynamicSecrets:
#     metadata:
#       name: my-vault-dynamic-secret
#       namespace: a-ns
#     spec:
#       # Vault path to obtain the dynamic secret from.
#       path: "/pki/issue/example-dot-com"
#       # Defaults to "POST"
#       # method: "POST"
#       # Parameters to pass to Vault write (for non-GET methods).
#       parameters:
#         common_name: "localhost"
#         ip_sans: "127.0.0.1,127.0.0.11"
#       # Defaults to "Data". "Auth" and "Raw" are also available
#       # resultType: "Data"
#       # Vault provider common spec.
#       provider:
#         server: "http://vault.default.svc.cluster.local:8200"
#         auth:
#           kubernetes:
#             mountPath: "kubernetes"
#             role: "external-secrets-operator"
#             serviceAccountRef:
#               name: "default"

passwords:
#   myPassword:
#     metadata:
#       name: my-password
#       namespace: a-ns
#     spec:
#       # To allow repeating characters.
#       allowRepeat: true
#       # Digits specifies the number of digits in the generated password. If omitted it defaults to 25% of the length of the password.
#       digits:
#       # Length of the password to be generated. Defaults to 32.
#       length: 32
#       # To disable uppercase characters.
#       noUpper: false
#       # Specifies the special characters that should be used in the generated password.
#       symbolCharacters: "-_$@"
#       # Specifies the number of symbol characters in the generated password. If omitted it defaults to 25% of the length of the password.
#       symbols:
