{{- range $k, $v := .Values.vaultDynamicSecrets }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata: {{- toYaml $v.metadata | nindent 2 }}
spec:
  path: {{ $v.spec.path }}
  method: {{ $v.spec.method | default "POST" }}
  parameters: {{- toYaml $v.spec.parameters | nindent 4 }}
  resultType: {{ $v.spec.resultType | default "Data" }}
  provider: {{- toYaml $v.spec.provider | nindent 4 }}
{{- end }}
